version: '3'
services:

  #PHP Service
  mpu-auth-app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: mpu-auth-app
    container_name: mpu-auth-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./src:/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /app
    networks:
      - auth-network
    depends_on:
      - mpu-auth-db
      - mpu-auth-composer

  mpu-auth-queue:
    image: ipunktbs/laravel-queue-worker:php7.4-v4.5
    container_name: mpu-auth-queue
    restart: unless-stopped
    tty: true
    environment:
      QUEUE_CONNECTION: database
    volumes:
      - ./src:/app
    networks:
      - auth-network
    depends_on:
      - mpu-auth-db
      - mpu-auth-composer

  #Nginx Service
  mpu-auth-webserver:
    image: nginx:alpine
    container_name: mpu-auth-webserver
    restart: unless-stopped
    tty: true
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      SERVER_NAME: ${SERVER_NAME}
      APP_NAME: ${APP_NAME}
    volumes:
      - ./src:/app
      - ./docker/nginx/conf.d/:/etc/nginx/templates/
    networks:
      - auth-network
    depends_on:
      - mpu-auth-app

  #Database Service
  mpu-auth-db:
    image: library/postgres:13.1-alpine
    container_name: mpu-auth-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    networks:
      - auth-network

  mpu-auth-composer:
    image: composer:2.0
    volumes:
      - ./src:/app
    working_dir: /app
    command: composer install

  mpu-auth-redis:
    image: "redis:alpine"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - auth-network

  mpu-auth-migrator:
    image: mpu-auth-app
    command: [ "/app/wait-for-it.sh", "mpu-auth-db:5432", "-t", "10", "--", "php", "/app/artisan", "migrate" ]
    volumes:
      - ./src:/app
    networks:
      - auth-network
    depends_on:
      - mpu-auth-composer
      - mpu-auth-db

#Docker Networks
networks:
  auth-network:
    driver: bridge
